BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBXXXX XXXXX XXXXX XXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXX XXXXX XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                BB BBBBBBBBB
                XXXXXXXXX XXXXXXX XXXX XXXXXXXXX XXX XXXX XXXXX XXXXXXXXX
                XXXXX XXXXXXXXXXXXXX
                    BBBBBBBBBB

                    BB BBBBBBBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXXXXXX XXXXXXXXXXX
                        BBBBBB
                    XXXXXX
                    BBBBB

                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXX XXXXXXXFFFFXXXXXX
                        BBBBB
                        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
                        BBBBBB
                    XXXXXX

                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
                        BBBBBB
                    XXXXXX

                    XXXX XXXXXXXXXXXXX XXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXXX
                BBBB
                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX XXXXXXX XXXX XXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXX XXX XXXXX XXX XX XXXXX XXXXXXXX XXXXXXX
                    XXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXX
                XXXXXX
                BBBBB
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB