BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBXXXX XXXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXX XXXX XXXXXX XXXXXXX XXXXXX
                XXXXXXXXXX XXXX XXXXXXXXX XXXXXXXX XX XX XXXXXX XXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB