BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBXXXXX XXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX XXXXX XXXXX XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXX XXXXX XXXX XXXX XXXXX
                    XXXXX XXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXX
                    BBBBBBBBBB
                    XXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX
                            XXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB