BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBBB BBBBBXXXXX XXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXX XXXXXXX XXXXX XXX XXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB