BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBB gettext(u'Qeydiyyat') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXX XXXXXXXXXXXXX gettext(u'Yeni Hesab Yarat') XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                    BBBBBBBBBB
                    FFFFFF
                    XXXX XXXXXXXXXXXXX XXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Qeydiyyatdan Keç') XXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXXXX
                     gettext(u'Artıq hesabınız var?')  XX XXXXXXBBB BBBBBBBXX gettext(u'Daxil olun') XXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB