XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXX
                    XXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXX XXXXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXX XXXX XXXXXX
                        XX XXXXXXXXX XXXXXXXXX  gettext(u'Ana Səhifəyə Qayıt') 
                    XXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX