BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXX

XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXBBBBB BBBBB gettext(u'Qiymətləndirmə Sistemi') BBBBBBBBXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXXX X
            XXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXXXX XXXXXXX XX XX XXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXX XXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX XXXXX XXXX XXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXXXXXX XX
        X

        XXXXXX
        XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        X

        XXXXXXXXXXXXXX XXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        X

        XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
            XXXXXXX XXXXXXXXXX
        X

        XXXXXXX X
            XXXXXXXXX XXXXXXX
            XXXX XX
            XXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXXXXX
        X

        XXXXXXXXXXXXXXXX X
            XXXXXXXXXXX XXX XXXX XXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXX XXXX
        X

        XX
        XXXXXXXXXX
        XXXXXXXXXXXXXX X
            XXXXXX XXXXXXXXXXXXXXXXXX
        X
    XXXXXXXX
XXXXXXX

XXXXXX
    XXXXXXXX
        XXXXXXXXX XX X
            XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXX XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Qiymətləndirmə Sistemi') XXXX
            XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                    XXX XXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBB
                            XXX BB BBBBBBBBBBBBBBBXXXXXXXXXXXXXX BBBBBX
                                XX XXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXXFFFFFFFFFFXXXXXX
                            XXXXX
                            BBBBBB
                        XXXXX
                    XXXXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                    XXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBBBBB
                        XXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
                            XXXXXXXXXXXXXXXXXXXXX XXXXXX
                        BBBBB
                        XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Salam') X XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                            XXXXXXXX XXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
                            XXXXXXXXX XXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                            XXXXX XXXXXXXX XXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX
                            XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'Superadmin') XXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXBBB BBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXBBBBBBBBBBXXXXXXX
                                XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX gettext(u'Çıxış') XXXXXXXXXXXXXXXX
                    XXXXX
                    BBBB
                    XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX gettext(u'Daxil Ol') XXXXXXXXX
                    BBBBB
                XXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXX
        BB BBBBBBBB
        BBB BBBBBBB BB BBBBBBBB
        XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
            
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        BBBBBB
        BBBBB

        BBBBB BBBBBBBBBBBBBBB
    XXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Qiymətləndirmə Sistemi')  XXXXXX BBB BBBXXXXXXX
        XXXXXX
    XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
            XXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXX X XX XX X
                XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    X XXX XXXXXXXXX XXXXXXXXXXXXXXXXXX
                    X XXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXX X XXXXXXXXX
                XXXXXXXXXXXXX
            XXX
            XXXXXXXXXXXXX
        XXX
    XXXXXXXXX
    BBBBB BBBBBBBBBBBBBBBB
XXXXXXX

XXXXXXX