BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Ana Səhifə') BBBBBBBB

BBBBB BBBBBBB

BB BBBBBBBBBB
XXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Aktiv İnkişaf Planınız') XXXXX
    XXX gettext(u'Sizin üçün')  XXXXXXXXXXXXXXXXX XX XXXXX XXXXXX XXXX XXX XXXXXXX XXXXX
        XXXXXXXXXXX XXXXXX
    XXXX
    XX XXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX gettext(u'Plana Bax') XXXX
XXXXXX
BBBBB
XXXX gettext(u'Qiymətləndirmə Tapşırıqlarınız') XXXXX
XXXX

BB BBBBBBBBBBBBBBBBB
XXX gettext(u'Aşağıdakı şəxslər üçün qiymətləndirməni tamamlamalısınız:') XXXX
XXXX XXXXXXXXXXXXXXXXXXX
    BBB B BB BBBBBBBBBBBBBBBBB
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX XX
        XXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Qiymətləndirmə dövrü') X XXXXXXXX
    XXXX
    BBBBBB
XXXXXX
BBBB
XXXX XXXXXXXXXXXX XXXXXXXXXXXXX
     gettext(u'Hal-hazırda tamamlanmalı qiymətləndirmə tapşırığınız yoxdur.') 
XXXXXX
BBBBB

BBBBBBBB