BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Qiymətləndirmə Hesabatı') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXXX  gettext(u'Qiymətləndirmə Hesabatı') 
        XXXXX
        XXXX XXXXXXXXXXXXX XXXXXXX
            BB BBB BBBBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBB
            BB BBBBBBBBBBB
            XX XXXXXXBBB BBBBBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXXX  gettext(u'Plana Bax') 
            XXXX
            BBBB
            XX XXXXXXBBB BBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX
                XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'İnkişaf Planı Yarat') 
            XXXX
            BBBBB
            BBBBB
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'PDF Yüklə') 
            XXXX
            BBBBB
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Hesabat Dövrünü Seçin:') XXXXXXXX
                XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX
                    BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
                    XXXXXXX XXXXXXXX BB BBBBBBBBBBBBBBBBBXXXXXXXXBBBBBX
                        
                    XXXXXXXXX
                    BBBBBB
                XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Göstər') XXXXXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX

    BB BBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        
    XXXXXX
    BBBB
    XXX XXXXXXXXXXXXX  gettext(u'Dövrü üçün Detallı Analiz') XXXXX
    XXXXXXXXXXX gettext(u'İşçi:') XXXXXXXXX XXXX

    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXX
            XXXX gettext(u'Kompetensiyalar üzrə Nəticələr') XXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX gettext(u'Ümumi Göstəricilər') XXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX
                        XXXX gettext(u'Kompetensiya (Kateqoriya)') XXXXX
                        XXXX gettext(u'Ortalama Xal (10 üzərindən)') XXXXX
                    XXXXX
                XXXXXXXX
                XXXXXXX
                    BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX
                        XXXXXXXXX
                        XXXXXXXXXXXXFFFFFFFFFFFFFXXXXXXXXXXXXXX
                    XXXXX
                    BBBBB
                    XXXX
                        XXX XXXXXXXXXXXX gettext(u'Bu dövr üçün göstərici tapılmadı.') XXXXX
                    XXXXX
                    BBBBBB
                XXXXXXXX
            XXXXXXXX
        XXXXXX
    XXXXXX

    XXX XXXXXXXXXXXXX
    XXXX  gettext(u'Dövrü üçün Yazılı Rəylər') XXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXX XXXXXXXXXXXXXXXXXXX
        BBB BBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBB
    XXXXX
    BBBB
    XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'Bu dövr üçün yazılı rəy qeyd edilməyib.') XXXX
    BBBBB
    BBBBB

    XXX XXXXXXXXXXXXX
    XXXX gettext(u'Performans Tarixçəsi (Ümumi Ortalama Bal)') XXXXX
    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        BB BBB BBBBBBBBBBBBBBBBBBBBBB
        XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX X
            XXX XXXXXXXXXXXXXXX X
                XXXXX XXXXXXXX
                XXXXX X
                    XXXXXXX  FFFFX
        XXXXXXXXX XX
            XXXXXX X gettext(u'Ortalama Xal') XX
            XXXXX  FFFFX
        XXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX
        XXXXXXXXXXXX XXXXXXXX XXXX XXXXXX
        XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXX
                    XX
                XX
        XXXXXXXX X
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX X
            XX X
                XXXXXXXXXXXXX XX
                XXXXXXXXXXXXX XX
            X
        X
    X
            XXX
        X
    BBBBB

    XXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XX XXXXXXXXXX X
        XXX XXXXXXXXXXXXXXX X
            XXXXX XXXXXXX
            XXXXX X
                XXXXXXX  FFFFX
    XXXXXXXXX XX
        XXXXXX X gettext(u'Ümumi Ortalama Bal') XX
        XXXXX  FFFFX
        XXXXX XXXXXX
        XXXXXXXXXXXX XXXXXXXXX XXX XXXXXX
        XXXXXXXX XXX
                    XX
                XX
    XXXXXXXX X
        XXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXXXXXXXX XXXXXX
                XXXXXXX X
            XX X
                XXXXXXXXXXXX XXXXX
                    XXXXXXXXXXXXX XX
            X
        X
    X
            XXX
        X
    XXX
XXXXXXXXX
BBBBBBBB