BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBB gettext(u'Fərdi İnkişaf Planı') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX gettext(u'Fərdi İnkişaf Planı') XXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXX gettext(u'İşçi:') XXXXXXXXX XXXX
            XXXXXXXX gettext(u'Qiymətləndirmə Dövrü:') XXXXXXXXX 
        XXXX
    XXXXXX

    XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXX XXXX XXXXXXXXXX XXXX XXXX XXXX XXXXXXX XXXXXXXXX XXXXX XXX XX XX
        XXXXXX XXXXXXXX XXXXXXX XXX XXXXXXXXXXXX XXXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        BBBBBBBBBB
        

        XXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXX XXXXXXXXXXXXX gettext(u'Hədəflər') XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                BBB BBBB BB BBBBBBB
                XXXX
                    XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXX XXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        FFFFFFFFFFFFFFF
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        FFFFFFFFFFFFFFF
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        FFFFFFFFFFFFFFF
                    XXXXXX
                    BB BBBBBBBBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXX
                        FFFFFFFFFFFFFFF
                    XXXXXX
                    BBBBB
                XXXXXX
                BBBBBB
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXX XXXXXX XXXXX XXXXXX XXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBX
                XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXX
                XXXXX XXXXXX XXXXXX
        XXXXXX
    XXXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
XXXXXXX
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
    X
XXXXXXXX
BBBBBBBB