BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Qiymətləndirmə Formu') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX gettext(u'Qiymətləndirmə Formu') XXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Qiymətləndirilən şəxs:')  XXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Dövr:')  XXXXXXXXXXXXXXXXXXXXX
    XXXXXX

    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        BBBBBBBBBB

        BBB BBBB BB BBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXX
                    BB BBBBBBBBBBBBBBBXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXBBBBB
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX gettext(u'Xal (1-dən 10-a qədər):') XXXXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX
                        BBB B BB BBBBBBBBBBBBBBBBBBBBBB
                        XXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                                XXXXXXXXXX XXXXXXXX XXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                XXXXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXX
                        BBBBBB
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXX XXX XXXXXXX
                        XXXXXXXX XXXXXXXXXX
                    XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXX
                        XXXXXXXXXXXXX gettext(u'Əlavə fikirlərinizi yaza bilərsiniz...') XXXXXXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        BBBBBB

        XXXX XXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                 gettext(u'Qiymətləndirməni Təsdiqlə') 
            XXXXXXXXX
        XXXXXX
    XXXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
XXXXXXX
    XXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
    X
XXXXXXXX
BBBBBBBB