BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Rəhbər Paneli') BBBBBBBB

BBBBB BBBBBBB
XXXX gettext(u'Rəhbər Paneli') XXXXX
XXXX

BB BBBBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXX XXXXXX
    XXXX XXXXXXXXXXXXXXX
        XXXX gettext(u'Komandanın Kompetensiyalar üzrə Performansı') XXXXX
        XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBB
XXXX gettext(u'Komanda Üzvləri') XXXXX
XXX gettext(u'Sizin tabeliyinizdə olan işçilərin siyahısı:') XXXX

BB BBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX
    BBB BBBBBB BB BBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXX
            XXXXXXXXXXXXXXXXX
            XXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXX gettext(u'Hesabata Bax') XXXX
    XXXXXX
    BBBBBB
XXXXXX
BBBB
XXXX XXXXXXXXXXXX XXXXXXXXXXXX
     gettext(u'Sizin tabeliyinizdə heç bir işçi tapılmadı.') 
XXXXXX
BBBBB

BBBBBBBB

BBBBB BBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX X
            XXX XXXXXXXXXXXXXXXXXXXX X
                XXXXX XXXXXX
                XXXXX X
                    XXXXXXX XX XXXXXXXXXXXXX XXXX X
    XX
        XXXXXXXXX XX
            XXXXXX X gettext(u'Komandanın Ortalama Balı') XX
            XXXXX  FFFFX
        XXXXXXXXXXXXXXXX X
            XXXXXXXXXX XXX XXXX XXXXXX
            XXXXXXXXX XXXX XXXX XXXXXX
            XXXXXXXXXX XXXX XXX XXXXXX
            XXXXXXXXX XXXX XXXX XXXXXX
            XXXXXXXXXX XXXX XXXX XXXXXX
            XXXXXXXXXX XXXX XXX XXXXX
        XX
        XXXXXXXXXXXX X
            XXXXXXXXXX XXX XXXX XXXX
            XXXXXXXXX XXXX XXXX XXXX
            XXXXXXXXXX XXXX XXX XXXX
            XXXXXXXXX XXXX XXXX XXXX
            XXXXXXXXXX XXXX XXXX XXXX
            XXXXXXXXXX XXXX XXX XXX
        XX
        XXXXXXXXXXXX X
                XX
            XX
        XXXXXXXX X
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX X
            XX X
                XXXXXXXXXXXX XXXXX
                XXXXXXXXXXXXX XX
            X
        XX
        XXXXXXXX X
            XXXXXXX X
                XXXXXXXX XXXXX
            X
        X
    X
        XXX
    X
XXX
XXXXXXXXX
BBBBBBBB