BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Superadmin Paneli') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
    XXX XXXXXXXXXXXXXXXX gettext(u'Superadmin Paneli') XXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX  gettext(u'Yeni Dövr Başlat') 
    XXXX
XXXXXX

BB BBB BBBB
XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX
    XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
     gettext(u'Sistemdə heç bir qiymətləndirmə dövrü tapılmadı. Zəhmət olmasa, yeni bir dövr başladın.') 
XXXXXX
BBBB
XXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Aktiv Dövr:')  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXX XXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXX gettext(u'Tamamlanma Nisbəti') XXXXX
                XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXX  gettext(u'tapşırıqdan')   XX XXXXX
                    XXXXXXXXXXXXX XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXX gettext(u'Departament Sayı') XXXXX
                XX XXXXXXXXXXXXXXXX XXXXXXXXXFFFFFFXXXX
                XX XXXXXXXXXXXXXXXXXX gettext(u'Prosesdə iştirak edən departamentlər') XXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX

XXX XXXXXXXXXXXXX

XXXX XXXXXXXXXX XXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Departamentlər üzrə Ortalama Performans') XXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Reytinq Cədvəli') XXXXXXX
                XXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXX
                            XXXX gettext(u'Departament') XXXXX
                            XXXX gettext(u'Ortalama Bal') XXXXX
                        XXXXX
                    XXXXXXXX
                    XXXXXXX
                        BBB BBBB BB BBBBBBBBBBBBBBBB
                        XXXX
                            XXXXXXXXX
                            XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXX
                        BBBBB
                        XXXX
                            XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Statistika üçün məlumat tapılmadı.') XXXXX
                        XXXXX
                        BBBBBB
                    XXXXXXXX
                XXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBB

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX X
            XXX XXXXXXXXXXXXXXXXXXXX X
                XXXXX XXXXXX
                XXXXX X
                    XXXXXXX XX XXXXXXXXXXXXX XXXX X
    XX
        XXXXXXXXX XX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX
            XXXXX  FFFFX
        XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXX XXXXXX
        XXXXXXXXXXXX XXXXXXXXX XXXX XXX XXXX
        XXXXXXXXXXXX X
                    XX
                XX
        XXXXXXXX X
        XXXXXXXXXX XXXX
        XXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX X
            XX X
                XXXXXXXXXXXX XXXXX
                XXXXXXXXXXXXX XX
            X
        XX
        XXXXXXXX X
            XXXXXXX X
                XXXXXXXX XXXXX
            X
        X
    X
            XXX
        X
    XXX
XXXXXXXXX
BBBBBBBB