BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBB gettext(u'Yeni Qiymətləndirmə Dövrü Yarat') BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXX XXXXXX gettext(u'Yeni Qiymətləndirmə Dövrü Yarat') XXXXX
    XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXX XXXXX XXXXXXXXXX XXXX XXX XXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXX XXXXX
        XXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
    XXX XXXXXXXXXXXXX

    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            BBBBBB BBBB
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
BBBBBBBB