"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-syucb&l%kj=-57_w-f64k&zuz=z2b#4p2la3)8+^5_1wi%#j-z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'core',
]

# Django-nun daxili tətbiqləri
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request', 
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.language_switcher_context', 
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'az'

TIME_ZONE = 'Asia/Baku'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# İstifadəçi modelini təyin edirik

AUTH_USER_MODEL = 'core.Ishchi'

# Authentication tənzimləmələri
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Crispy Forms tənzimləmələri
# Crispy Forms, Django formalarını daha gözəl və funksional etmək üçün istifadə olunur.

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Jazzmin tənzimləmələri
# Jazzmin, Django admin panelini daha gözəl və funksional etmək üçün istifadə olunan bir tətbiqdir.

JAZZMIN_SETTINGS = {
    # Saytın brauzer başlığı
    "site_title": "360° Qiymətləndirmə Paneli",

    # Navbar və login səhifəsindəki başlıq
    "site_header": "İşçi Dəyərləndirmə Sistemi",

    # Panel brendi
    "site_brand": "360° Dəyərləndirmə",

    # Loqo (əgər varsa, əlavə et: static/images/logo.png)
    # "site_logo": "images/logo.png",
    # "login_logo": "images/logo.png",

    # Loqo tipli favicon
    # "site_icon": "images/favicon.ico",

    # Xoş gəlmisiniz mətni
    "welcome_sign": "360° Qiymətləndirmə Sisteminizə Xoş Gəlmisiniz",

    # Admin başlığının sol üst hissəsi
    "site_header_short": "Dəyərləndirmə",

    # Əsas sayt linki (brend kliklənəndə yönləndiriləcək ünvan)
    "site_url": "/",

    # Dəyişikliklər haqqında məlumat paneli göstərilsinmi?
    "show_sidebar": True,

    # Menyu başlıqları ilə ayrılmalıdırmı?
    "navigation_expanded": True,

    # Əlavə başlıqlar
    "topmenu_links": [
        {"name": "Ana Səhifə", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"app": "your_app_label"},  # Əgər tam app göstərmək istəyirsənsə
    ],

    # Alt menu strukturu (sıralama və qruplaşma)
    "custom_links": {
        "auth": [
            {
                "name": "İstifadəçi əlavə et",
                "url": "add_user",  # custom view varsa
                "icon": "fas fa-user-plus",
                "permissions": ["auth.add_user"]
            }
        ]
    },

    # Admin səhifəsinin alt hissəsi
    "copyright": "© 2025 Muradov İT MMC",

    # UI Builder-i göstərmək
    "show_ui_builder": True,

    # Model konfiqurasiya (görünüş optimallaşdırması)
    "order_with_respect_to": ["Qiymetlendirme", "Ishci", "Rehber"],
    
    # İstifadəçi menyusunda nə göstərilsin
    "user_avatar": None,
}


JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",  # Alternativ: "solar", "cyborg", "superhero"
    "dark_mode_theme": "darkly",

    "navbar": "navbar-dark navbar-primary",
    "brand_colour": "navbar-primary",
    "accent": "accent-info",

    "navbar_small_text": False,
    "brand_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,

    "sidebar": "sidebar-dark-primary",
    "sidebar_fixed": True,
    "sidebar_nav_small_text": False,
    "sidebar_nav_flat_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_compact_style": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,

    "layout_boxed": False,
    "navbar_fixed": True,
    "footer_fixed": True,

    "button_classes": {
        "primary": "btn btn-primary",
        "secondary": "btn btn-secondary",
        "info": "btn btn-info",
        "warning": "btn btn-warning",
        "danger": "btn btn-danger",
        "success": "btn btn-success"
    }
}


from django.utils.translation import gettext_lazy as _

# Saytda mövcud olacaq dillər
LANGUAGES = [
    ('az', _('Azərbaycan')),
    ('en', _('English')),
]

# Tərcümə fayllarının yerləşəcəyi qovluq
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# --- E-POÇT TƏNZİMLƏMƏLƏRİ ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'muradofftehmez01@gmail.com'
EMAIL_HOST_PASSWORD = 'juuu wxbb gcvw cbhj'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
