# config/settings.py

"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.2.2.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.utils.translation import gettext_lazy as _

# ------------------------------------------------------------------------------
# ƏSAS TƏNZİMLƏMƏLƏR VƏ YOLLAR (BASE CONFIGURATION & PATHS)
# ------------------------------------------------------------------------------

# .env faylındakı dəyişənləri yükləyirik
load_dotenv()

# Layihənin kök qovluğu
BASE_DIR = Path(__file__).resolve().parent.parent


# ------------------------------------------------------------------------------
# TƏHLÜKƏSİZLİK (SECURITY)
# ------------------------------------------------------------------------------

# GİZLİ AÇAR: Həssas məlumatları .env faylından oxuyuruq
SECRET_KEY = os.getenv('SECRET_KEY')

# DEBUG REJİMİ: Production mühitində mütləq False olmalıdır!
DEBUG = os.getenv('DEBUG', 'False') == 'true'
# ALLOWED_HOSTS: Yalnız lokal hostlar üçün icazə verilir

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# ------------------------------------------------------------------------------
# TƏTBİQLƏR (APPLICATIONS)
# ------------------------------------------------------------------------------

INSTALLED_APPS = [
    # Xarici tətbiqlər (dizayn və s.)
    'jazzmin',
    'crispy_forms',
    'crispy_bootstrap5',
    'simple_history',
    
    # Django-nun daxili tətbiqləri
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Bizim lokal tətbiqimiz
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # Dil üçün
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware', # Tarixçə üçün
]

ROOT_URLCONF = 'config.urls'

WSGI_APPLICATION = 'config.wsgi.application'


# ------------------------------------------------------------------------------
# VERİLƏNLƏR BAZASI (DATABASE)
# ------------------------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ------------------------------------------------------------------------------
# ŞİFRƏ YOXLAMALARI (PASSWORD VALIDATION)
# ------------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ------------------------------------------------------------------------------
# BEYNƏLXALQLAŞDIRMA VƏ LOKALLAŞDIRMA (I18N & L10N)
# ------------------------------------------------------------------------------

LANGUAGE_CODE = 'az'
TIME_ZONE = 'Asia/Baku'
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ('az', _('Azərbaycan')),
    ('en', _('English')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# ------------------------------------------------------------------------------
# STATİK FAYLLAR (STATIC FILES)
# ------------------------------------------------------------------------------

STATIC_URL = 'static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles' # Deployment üçün lazım olacaq


# ------------------------------------------------------------------------------
# AUTENTİFİKASİYA (AUTHENTICATION)
# ------------------------------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'core.Ishchi'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


# ------------------------------------------------------------------------------
# E-POÇT TƏNZİMLƏMƏLƏRİ (EMAIL SETTINGS)
# ------------------------------------------------------------------------------

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# ------------------------------------------------------------------------------
# XARİCİ PAKETLƏRİN TƏNZİMLƏMƏLƏRİ (THIRD-PARTY PACKAGES)
# ------------------------------------------------------------------------------

# Crispy Forms Tənzimləmələri
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# Jazzmin Admin Paneli Tənzimləmələri
JAZZMIN_SETTINGS = {
    # Saytın brauzer başlığı
    "site_title": "360° Qiymətləndirmə Paneli",

    # Navbar və login səhifəsindəki başlıq
    "site_header": "İşçi Dəyərləndirmə Sistemi",

    # Panel brendi
    "site_brand": "360° Dəyərləndirmə",

    # Loqo (əgər varsa, əlavə et: static/images/logo.png)
    # "site_logo": "images/logo.png",
    # "login_logo": "images/logo.png",

    # Loqo tipli favicon
    # "site_icon": "images/favicon.ico",

    # Xoş gəlmisiniz mətni
    "welcome_sign": "360° Qiymətləndirmə Sisteminizə Xoş Gəlmisiniz",

    # Admin başlığının sol üst hissəsi
    "site_header_short": "Dəyərləndirmə",

    # Əsas sayt linki (brend kliklənəndə yönləndiriləcək ünvan)
    "site_url": "/",

    # Dəyişikliklər haqqında məlumat paneli göstərilsinmi?
    "show_sidebar": True,

    # Menyu başlıqları ilə ayrılmalıdırmı?
    "navigation_expanded": True,

    # Əlavə başlıqlar
    "topmenu_links": [
        {"name": "Ana Səhifə", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"app": "your_app_label"},  # Əgər tam app göstərmək istəyirsənsə
    ],

    # Alt menu strukturu (sıralama və qruplaşma)
    "custom_links": {
        "auth": [
            {
                "name": "İstifadəçi əlavə et",
                "url": "add_user",  # custom view varsa
                "icon": "fas fa-user-plus",
                "permissions": ["auth.add_user"]
            }
        ]
    },

    # Admin səhifəsinin alt hissəsi
    "copyright": "© 2025 Muradov İT MMC",

    # UI Builder-i göstərmək
    "show_ui_builder": True,

    # Model konfiqurasiya (görünüş optimallaşdırması)
    "order_with_respect_to": ["Qiymetlendirme", "Ishci", "Rehber"],
    
    # İstifadəçi menyusunda nə göstərilsin
    "user_avatar": None,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-lime",
    "navbar": "navbar-success navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "slate",
    "dark_mode_theme": "slate",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-outline-success"
        
    },
    "actions_sticky_top": False
}


# ------------------------------------------------------------------------------
# ŞABLONLAR (TEMPLATES)
# ------------------------------------------------------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request', 
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.language_switcher_context', 
            ],
        },
    },
]