BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Xəta') BBBBBBBB

BBBBB BBBBBBB
 gettext(u'Səhv Sorğu') 
 gettext(u'Sorğunuz düzgün deyil və emal edilə bilmədi.') 
XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX XX
BBBBBBBB