BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Çoxlu Sorğu') BBBBBBBB

BBBBB BBBBBBB
 gettext(u'Çoxlu Sorğu') 
XX XXXXX XXXX XXXX XXXXXX XXXXXXX XXX XXXXX XXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXX XXX XX XXXXX XXXXXXX XXXX XXXXXX XX
XXXXXXXXXXXXX XX
XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
BBBBBBBB