BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Server Xətası') BBBBBBBB

BBBBB BBBBBBB
 gettext(u'Server Xətası') 
 gettext(u'Daxili server xətası baş verdi. Komandamız problemi araşdırır.') 
XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXX XX
BBBBBBBB