BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Keçid Xətası') BBBBBBBB

BBBBB BBBBBBB
 gettext(u'Keçid Xətası') 
XX XXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXX XXXXX XXX XXXXXXXXX XXXXXX XXXXX XXX XXXXXXXXX XX XXXXXXXXXXXXX
XX
XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXX XX
BBBBBBBB