BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBB gettext(u'Texniki Xidmət') BBBBBBBB

BBBBB BBBBBBB
 gettext(u'Texniki Xidmət') 
 gettext(u'Hazırda sistemdə texniki xidmət aparılır. Qısa zamanda geri dönəcəyik.') 
XX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXX XX
BBBBBBBB